import {initializeApp} from "https://www.gstatic.com/firebasejs/10.13.2/firebase-app.js";
import {getAuth,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,setDoc,deleteDoc,getDoc,serverTimestamp,query,orderBy} from "https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js";
import {getFunctions,httpsCallable} from "https://www.gstatic.com/firebasejs/10.13.2/firebase-functions.js";
const cfg={apiKey:"AIzaSyATRvlq7VzIYFrVSprw5yVzv0uu5d-QrVM",authDomain:"medsbox-pro.firebaseapp.com",projectId:"medsbox-pro",storageBucket:"medsbox-pro.firebasestorage.app",messagingSenderId:"145094360411",appId:"1:145094360411:web:c8a525881927c294682e7e"};
const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),fn=getFunctions(app),createCode=httpsCallable(fn,'createActivationCode');
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let cache={apps:[],plans:[],codes:[],users:[]};
function go(name){document.querySelectorAll('.admin-section').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$('pageTitle').textContent={overview:'نظرة عامة',apps:'التطبيقات',plans:'الاشتراكات',codes:'أكواد التفعيل',users:'المستخدمون'}[name]||name}
function modal(html){$('formContent').innerHTML=html;$('formOverlay').classList.add('open')};function close(){ $('formOverlay').classList.remove('open') }
async function loadAll(){const [a,p,c,u]=await Promise.all([getDocs(collection(db,'apps')),getDocs(collection(db,'plans')),getDocs(collection(db,'activationCodes')),getDocs(collection(db,'users'))]);cache={apps:a.docs.map(d=>({id:d.id,...d.data()})),plans:p.docs.map(d=>({id:d.id,...d.data()})),codes:c.docs.map(d=>({id:d.id,...d.data()})),users:u.docs.map(d=>({id:d.id,...d.data()}))};render()}
function render(){ $('statApps').textContent=cache.apps.length;$('statPlans').textContent=cache.plans.length;$('statUsers').textContent=cache.users.length;$('statCodes').textContent=cache.codes.filter(x=>x.status==='unused').length;
$('appsTable').innerHTML=`<table class="data-table"><thead><tr><th>التطبيق</th><th>التصنيف</th><th>الإصدار</th><th>الحالة</th><th></th></tr></thead><tbody>${cache.apps.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.category)}</td><td>${esc(x.version||'—')}</td><td><span class="pill">${x.active===false?'مخفي':'ظاهر'}</span></td><td><button class="btn btn-glass small" data-edit-app="${x.id}">تعديل</button> <button class="btn btn-glass small" data-del-app="${x.id}">حذف</button></td></tr>`).join('')}</tbody></table>`;
$('plansTable').innerHTML=`<table class="data-table"><thead><tr><th>الخطة</th><th>السعر</th><th>المدة</th><th>الحالة</th><th></th></tr></thead><tbody>${cache.plans.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.price)} ${esc(x.currency||'USD')}</td><td>${x.durationDays?x.durationDays+' يوم':'مدى الحياة'}</td><td>${x.active===false?'مخفية':'فعالة'}</td><td><button class="btn btn-glass small" data-edit-plan="${x.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`;
$('codesTable').innerHTML=`<table class="data-table"><thead><tr><th>الكود</th><th>الخطة</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>${cache.codes.slice().reverse().map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.planId)}</td><td><span class="pill">${esc(x.status)}</span></td><td>${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('ar-IQ'):'—'}</td></tr>`).join('')}</tbody></table>`;
$('usersTable').innerHTML=`<table class="data-table"><thead><tr><th>البريد</th><th>الاسم</th><th>الخطة</th><th>الحالة</th></tr></thead><tbody>${cache.users.map(x=>`<tr><td dir="ltr">${esc(x.email)}</td><td>${esc(x.fullname)}</td><td>${esc(x.plan||'—')}</td><td><span class="pill">${esc(x.subscriptionStatus||'pending')}</span></td></tr>`).join('')}</tbody></table>`}
function appForm(a={}){modal(`<p class="kicker">Catalog</p><h2>${a.id?'تعديل التطبيق':'إضافة تطبيق'}</h2><form id="appForm" class="admin-form"><div class="form-grid"><label>اسم التطبيق<input name="name" required value="${esc(a.name)}"></label><label>المعرف (slug)<input name="id" required value="${esc(a.id||'')}" ${a.id?'readonly':''}></label></div><div class="form-grid"><label>التصنيف<input name="category" required value="${esc(a.category)}"></label><label>الإصدار<input name="version" value="${esc(a.version||'')}" placeholder="1.0.0"></label></div><label>الوصف<textarea name="description">${esc(a.description||'')}</textarea></label><label>رابط الأيقونة<input name="iconUrl" value="${esc(a.iconUrl||'')}" placeholder="https://..."></label><label>المنصات (مفصولة بفاصلة)<input name="platforms" value="${esc((a.platforms||[]).join(','))}" placeholder="Android,iPhone,iPad"></label><label>روابط التحميل — JSON<textarea name="links">${esc(JSON.stringify(a.downloadLinks||{},null,2))}</textarea></label><label><input type="checkbox" name="active" ${a.active!==false?'checked':''}> إظهار في المكتبة العامة</label><button class="btn btn-primary full">حفظ التطبيق</button></form>`);$('appForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);let links={};try{links=JSON.parse(f.get('links')||'{}')}catch{alert('صيغة روابط التحميل يجب أن تكون JSON صحيحة');return}const id=f.get('id').trim();await setDoc(doc(db,'apps',id),{name:f.get('name').trim(),category:f.get('category').trim(),version:f.get('version').trim(),description:f.get('description').trim(),iconUrl:f.get('iconUrl').trim(),platforms:f.get('platforms').split(',').map(x=>x.trim()).filter(Boolean),downloadLinks:links,active:f.get('active')==='on',updatedAt:serverTimestamp()},{merge:true});close();loadAll()}}
function planForm(p={}){modal(`<p class="kicker">Subscriptions</p><h2>${p.id?'تعديل الخطة':'إضافة خطة'}</h2><form id="planForm" class="admin-form"><label>المعرف<input name="id" required value="${esc(p.id||'')}" ${p.id?'readonly':''} placeholder="yearly"></label><div class="form-grid"><label>اسم الخطة<input name="name" required value="${esc(p.name)}"></label><label>السعر<input name="price" type="number" step="0.01" required value="${esc(p.price||'10')}"></label></div><div class="form-grid"><label>العملة<input name="currency" value="${esc(p.currency||'USD')}"></label><label>المدة بالأيام<input name="durationDays" type="number" value="${esc(p.durationDays||365)}" placeholder="اتركه فارغاً للدائم"></label></div><label>الوصف<textarea name="description">${esc(p.description||'')}</textarea></label><label><input type="checkbox" name="active" ${p.active!==false?'checked':''}> فعالة</label><button class="btn btn-primary full">حفظ الخطة</button></form>`);$('planForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),days=f.get('durationDays');await setDoc(doc(db,'plans',f.get('id').trim()),{name:f.get('name').trim(),price:Number(f.get('price')),currency:f.get('currency').trim()||'USD',durationDays:days?Number(days):null,description:f.get('description').trim(),active:f.get('active')==='on',updatedAt:serverTimestamp()},{merge:true});close();loadAll()}}
$('newAppBtn').onclick=()=>appForm();$('newPlanBtn').onclick=()=>planForm();$('newCodeBtn').onclick=async()=>{modal(`<p class="kicker">Activation</p><h2>إنشاء كود تفعيل</h2><form id="codeGen" class="admin-form"><label>الخطة<select name="plan"><option value="yearly">سنوي</option><option value="lifetime">مدى الحياة</option></select></label><label>مدة السنوي بالأيام<input name="days" type="number" value="365"></label><label>ملاحظة<input name="note" placeholder="مثلاً: طلب #MSB..." ></label><button class="btn btn-primary full">إنشاء الكود</button></form><div id="codeResult"></div>`);$('codeGen').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const r=await createCode({planId:f.get('plan'),durationDays:Number(f.get('days')),note:f.get('note')});$('codeResult').innerHTML=`<div class="code-result">${esc(r.data.code)}</div><p>انسخ الكود وأرسله للمشترك عبر تيليجرام.</p>`;loadAll()}catch{alert('تعذر إنشاء الكود')}}};
document.addEventListener('click',async e=>{const x=e.target.closest('[data-go]');if(x)go(x.dataset.go);const s=e.target.closest('[data-section]');if(s)go(s.dataset.section);const ea=e.target.closest('[data-edit-app]');if(ea)appForm(cache.apps.find(x=>x.id===ea.dataset.editApp));const ep=e.target.closest('[data-edit-plan]');if(ep)planForm(cache.plans.find(x=>x.id===ep.dataset.editPlan));const da=e.target.closest('[data-del-app]');if(da&&confirm('حذف التطبيق؟')){await deleteDoc(doc(db,'apps',da.dataset.delApp));loadAll()}});$('formClose').onclick=close;$('formOverlay').addEventListener('click',e=>{if(e.target===$('formOverlay'))close()});$('logoutBtn').onclick=()=>signOut(auth).then(()=>location.href='index.html');
onAuthStateChanged(auth,async user=>{if(!user)return location.href='index.html?open=login';const a=await getDoc(doc(db,'admins',user.uid));if(!a.exists()||a.data().enabled!==true){document.body.innerHTML='<main class="admin-shell"><section class="panel glass-card"><h1>غير مصرح</h1><p>هذا الحساب ليس ضمن مسؤولي MedSBoX.</p><a class="btn btn-primary" href="index.html">العودة</a></section></main>';return}$('adminEmail').textContent=user.email;loadAll()});
