(() => {
  const STORAGE_KEY='medsbox-theme',media=window.matchMedia('(prefers-color-scheme: dark)'),root=document.documentElement,publicPages=['index.html','library.html','offers.html','ios-store.html','payment.html','activation.html'],isPublic=publicPages.includes(location.pathname.split('/').pop()||'index.html');
  const getPreference=()=>localStorage.getItem(STORAGE_KEY)||'system',isDark=p=>p==='dark'||(p==='system'&&media.matches);
  const apply=p=>{root.dataset.theme=isDark(p)?'dark':'light';root.dataset.themePreference=p;const icon=document.getElementById('themeIcon'),label=document.getElementById('themeCurrent');if(icon)icon.className=`fa-solid ${p==='dark'?'fa-moon':p==='light'?'fa-sun':'fa-desktop'}`;if(label)label.textContent=p.charAt(0).toUpperCase()+p.slice(1);document.querySelectorAll('[data-theme-choice]').forEach(b=>{const active=b.dataset.themeChoice===p;b.classList.toggle('active',active);b.setAttribute('aria-checked',String(active))})};
  const normalizePublicFlow=()=>{if(!isPublic)return;document.querySelectorAll('#accountBtn').forEach(el=>el.remove());document.querySelectorAll('a[href*="open=register"],a[href*="open=login"]').forEach(a=>{a.href='payment.html';a.textContent='Subscribe & activate'});document.querySelectorAll('a,button').forEach(el=>{const t=(el.textContent||'').trim();if(/^(Sign in|Sign out|Create account|Register|Forgot password)$/i.test(t)){el.textContent='Subscribe & activate';if(el.tagName==='A')el.href='payment.html'}})};
  const addMobileNav=()=>{if(document.body.classList.contains('admin-page')||document.querySelector('.vision-bottom-nav'))return;const path=location.pathname.split('/').pop()||'index.html',active=k=>(k==='home'&&(path===''||path==='index.html'))||(k==='library'&&path==='library.html')||(k==='apple'&&path==='ios-store.html')||(k==='plans'&&path==='payment.html');const nav=document.createElement('nav');nav.className='vision-bottom-nav';nav.setAttribute('aria-label','Quick navigation');nav.innerHTML=`<a href="index.html" class="${active('home')?'active':''}"><i class="fa-solid fa-house"></i><span>Home</span></a><a href="library.html" class="${active('library')?'active':''}"><i class="fa-solid fa-table-cells"></i><span>Library</span></a><a href="ios-store.html" class="${active('apple')?'active':''}"><i class="fa-brands fa-apple"></i><span>Apple</span></a><a href="payment.html" class="${active('plans')?'active':''}"><i class="fa-solid fa-star"></i><span>Subscribe</span></a><a href="https://t.me/ID29i" target="_blank" rel="noopener" aria-label="Support"><i class="fa-brands fa-telegram"></i><span>Support</span></a>`;document.body.appendChild(nav);let lastY=window.scrollY,ticking=false;const sync=()=>{const y=window.scrollY,d=y-lastY;if(Math.abs(d)>8){const hidden=d>0&&y>120;nav.style.transform=hidden?'translateY(calc(120% + env(safe-area-inset-bottom)))':'translateY(0)';nav.style.opacity=hidden?'0':'1';nav.style.pointerEvents=hidden?'none':'auto';lastY=y}ticking=false};window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(sync);ticking=true}},{passive:true})};
  const addPageInteractions=()=>{const header=document.querySelector('.header');let ticking=false;const sync=()=>{if(header)header.classList.toggle('scrolled',window.scrollY>24);ticking=false};window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(sync);ticking=true}},{passive:true});sync();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const targets=document.querySelectorAll('.section,.hero-card,.app-card,.store-app,.ios-plan,.pay-step,.social-card,.support-note,.activation-card,.access-notice,.empty-state');if(!('IntersectionObserver'in window))return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('vf-visible');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -7% 0px'});targets.forEach((el,i)=>{el.classList.add('vf-reveal');el.style.setProperty('--vf-delay',`${Math.min(i%5,4)*45}ms`);observer.observe(el)})};
  const init=()=>{apply(getPreference());normalizePublicFlow();addMobileNav();addPageInteractions();const button=document.getElementById('themeButton'),menu=document.getElementById('themeMenu');if(button&&menu){button.addEventListener('click',e=>{e.stopPropagation();const open=menu.classList.toggle('open');button.setAttribute('aria-expanded',String(open))});menu.querySelectorAll('[data-theme-choice]').forEach(c=>c.addEventListener('click',()=>{localStorage.setItem(STORAGE_KEY,c.dataset.themeChoice);apply(c.dataset.themeChoice);menu.classList.remove('open');button.setAttribute('aria-expanded','false')}));document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==button){menu.classList.remove('open');button.setAttribute('aria-expanded','false')}})}};media.addEventListener?.('change',()=>{if(getPreference()==='system')apply('system')});window.addEventListener('DOMContentLoaded',init);
})();
