const { onCall, HttpsError } = require('firebase-functions/v2/https');
const { onSchedule } = require('firebase-functions/v2/scheduler');
const { initializeApp } = require('firebase-admin/app');
const { getFirestore, FieldValue, Timestamp } = require('firebase-admin/firestore');
const { getStorage } = require('firebase-admin/storage');
const crypto = require('crypto');
initializeApp();
const db=getFirestore(); const bucket=getStorage().bucket();
async function admin(uid){if(!uid)return false;const s=await db.doc(`admins/${uid}`).get();return s.exists&&s.data().enabled===true;}
function makeCode(){const x=crypto.randomBytes(8).toString('hex').toUpperCase();return `MSB-${x.slice(0,4)}-${x.slice(4,8)}-${x.slice(8,12)}-${x.slice(12,16)}`;}
function makeOrderId(){return `MSB-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;}
exports.createOrder=onCall(async r=>{const uid=r.auth?.uid;if(!uid)throw new HttpsError('unauthenticated','Login required');const planId=String(r.data?.planId||'').trim(),reference=String(r.data?.reference||'').trim().toUpperCase();if(!planId||!reference)throw new HttpsError('invalid-argument','Plan and reference required');const [ps,us]=await Promise.all([db.doc(`plans/${planId}`).get(),db.doc(`users/${uid}`).get()]);if(!ps.exists||ps.data().active===false)throw new HttpsError('not-found','Plan not found');if(!us.exists)throw new HttpsError('failed-precondition','Profile missing');const p=ps.data(),orderId=makeOrderId();await db.doc(`orders/${orderId}`).set({orderId,userId:uid,email:us.data().email||r.auth.token?.email||'',planId,planName:p.name||planId,amount:Number(p.price),currency:p.currency||'USD',reference,paymentMethod:'Telegram',status:'pending',createdAt:FieldValue.serverTimestamp()});return{orderId,reference,planId,planName:p.name,amount:Number(p.price),currency:p.currency||'USD'};});
exports.createActivationCode=onCall(async r=>{const uid=r.auth?.uid;if(!(await admin(uid)))throw new HttpsError('permission-denied','Admin only');const planId=String(r.data?.planId||'').trim(),orderId=String(r.data?.orderId||'').trim();if(!planId)throw new HttpsError('invalid-argument','Plan required');const p=await db.doc(`plans/${planId}`).get();if(!p.exists||p.data().active===false)throw new HttpsError('not-found','Plan not found');let order=null;if(orderId){const o=await db.doc(`orders/${orderId}`).get();if(!o.exists)throw new HttpsError('not-found','Order not found');order=o.data();if(order.planId!==planId)throw new HttpsError('failed-precondition','Order plan mismatch');if(['activated','code_issued'].includes(order.status))throw new HttpsError('failed-precondition','Order already processed');}const raw=p.data().durationDays;const durationDays=raw==null?null:Math.max(1,Number(r.data?.durationDays||raw));const code=makeCode();await db.doc(`activationCodes/${code}`).set({code,planId,durationDays,status:'unused',orderId:orderId||null,userId:order?.userId||null,note:String(r.data?.note||''),createdBy:uid,createdAt:FieldValue.serverTimestamp()});if(orderId)await db.doc(`orders/${orderId}`).update({status:'code_issued',codeId:code,activatedAt:null,codeIssuedAt:FieldValue.serverTimestamp()});return{code,planId,durationDays,orderId:orderId||null};});
exports.redeemActivationCode=onCall(async r=>{const uid=r.auth?.uid;if(!uid)throw new HttpsError('unauthenticated','Login required');const id=String(r.data?.code||'').trim().toUpperCase();if(!id)throw new HttpsError('invalid-argument','Code required');const ref=db.doc(`activationCodes/${id}`),userRef=db.doc(`users/${uid}`),now=Timestamp.now();let out;await db.runTransaction(async tx=>{const c=await tx.get(ref),u=await tx.get(userRef);if(!c.exists||c.data().status!=='unused')throw new HttpsError('not-found','Invalid or used code');if(!u.exists)throw new HttpsError('failed-precondition','Profile missing');const d=c.data();if(d.userId&&d.userId!==uid)throw new HttpsError('permission-denied','Code belongs to another account');const expiresAt=d.durationDays==null?null:Timestamp.fromMillis(now.toMillis()+Number(d.durationDays)*86400000);tx.update(ref,{status:'used',usedBy:uid,usedAt:FieldValue.serverTimestamp()});tx.update(userRef,{plan:d.planId,subscriptionStatus:'active',startedAt:FieldValue.serverTimestamp(),activatedAt:FieldValue.serverTimestamp(),expiresAt});if(d.orderId)tx.update(db.doc(`orders/${d.orderId}`),{status:'activated',activatedAt:FieldValue.serverTimestamp(),activatedUserId:uid});out={planId:d.planId,expiresAt:expiresAt?expiresAt.toDate().toISOString():null};});return{success:true,...out};});
exports.createDownloadToken=onCall(async r=>{const uid=r.auth?.uid;if(!uid)throw new HttpsError('unauthenticated','Login required');const appId=String(r.data?.appId||''),platform=String(r.data?.platform||'');const us=await db.doc(`users/${uid}`).get(),u=us.data()||{};const active=u.subscriptionStatus==='active'&&(!u.expiresAt||u.expiresAt.toMillis()>Date.now());if(!active)throw new HttpsError('permission-denied','Active subscription required');const a=await db.doc(`apps/${appId}`).get();if(!a.exists||a.data().active!==true)throw new HttpsError('not-found','App not found');const path=a.data().storagePaths?.[platform];if(!path||!path.startsWith(`app-assets/${appId}/`))throw new HttpsError('not-found','File unavailable');const [url]=await bucket.file(path).getSignedUrl({version:'v4',action:'read',expires:Date.now()+600000});await db.collection('downloadLogs').add({userId:uid,appId,platform,createdAt:FieldValue.serverTimestamp()});return{url};});
exports.expireSubscriptions=onSchedule('every 24 hours',async()=>{const now=Timestamp.now(),s=await db.collection('users').where('subscriptionStatus','==','active').where('expiresAt','<=',now).get();if(s.empty)return null;const b=db.batch();s.docs.forEach(d=>b.update(d.ref,{subscriptionStatus:'expired'}));await b.commit();return null;});
